---
- name: Deploying a laravel app
  hosts: all
  vars:
    db_user: demoproject
    db_pass: demoproject
    db_name: demoproject
    diretory: suleiman-demo-project
    app_name: laravel

  tasks:

    - name: Artisan Key Gen
      shell: cd ~/suleiman-demo-project/laravel && php artisan key:generate && cd

    - name: Artisan config clear cache
      shell: cd ~/suleiman-demo-project/laravel && php artisan config:cache && cd
 
    - name: Artisan migrate fresh
      shell: cd ~/suleiman-demo-project/laravel && php artisan migrate:fresh && cd

    - name: Artisan migrate refresh	
      shell: cd ~/suleiman-demo-project/laravel && php artisan migrate:refresh && cd