---
- name: Deploying a laravel app
  hosts: all
  become: true
  become_method: sudo
  vars:
    db_user: demoproject
    db_pass: demoproject
    db_name: demoproject
    diretory: suleiman-demo-project
    app_name: laravel

  tasks:

    - name: Download and install Composer
      shell: curl -sS https://getcomposer.org/installer | php
      args:
        chdir: /usr/src/
        creates: /usr/local/bin/composer
        warn: false
      become: yes

    - name: Add Composer to global path
      copy: 
        remote_src: yes
        src: /usr/src/composer.phar      
        dest: /usr/local/bin/composer
        group: root
        mode: '0777'
        owner: root
      become: yes

    - name: "Composer  install"
      become: false
      composer:
        command: install
        global_command: false
        working_dir: ~/suleiman-demo-project/laravel
    
    - name: Composer create project
      become: false
      composer:
        command: create-project
        global_command: false
        working_dir: ~/suleiman-demo-project/laravel

