---
- name: Deploying a laravel app
  hosts: all
  become: true
  become_method: sudo
  vars:
    db_user: demoproject
    db_pass: demoproject
    db_name: demoproject
    diretory: suleiman-demo-project
    app_name: laravel

  tasks:
    - name: updating and upgrading apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'
    
    - name: Getting mysql .deb url
      get_url: 
        url="https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb"
        dest="$HOME/mysql-apt-config_0.8.22-1_all.deb"
 
    - name: Install mysql .deb package
      apt: deb="$HOME/mysql-apt-config_0.8.22-1_all.deb"

    - name: install pip3
      apt:
        name: python3-pip 
        state: present

    - name: Install pymysql python package
      ansible.builtin.pip:
        name: pymysql

    - name: Installing mysql-server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: start and enable mysql
      service:
        name: mysql
        state: started
        enabled: yes

    - name: creating mysql user demoproject
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_pass}}"
        priv: '*.*:ALL'
        host: 'localhost'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

    - name: creating laravel
      mysql_db:
        name: "{{db_name}}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
   
    - name: Enable remote login to mysql
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
    
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
    
    - name: Copy PostgreSQL script to remote server
      copy:
        src: ~/ansible/files/postgresql.sh
        dest: ~/postgresql.sh
        owner: vagrant
        group: vagrant
        mode: 0777
      
    - name: Executing PostgreSQL script on remote server
      shell: bash ~/postgresql
      ignore_errors: true
