---
- name: Deploying a laravel app
  hosts: all
  become: true
  become_method: sudo
  vars:
    db_user: demoproject
    db_pass: demoproject
    db_name: demoproject

  tasks:
    - name: changing timezone
      timezone:
          name: Africa/Lagos

    - name: installing net-tools
      apt:
          name: net-tools
          state: present

    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Installing some dependencies
      package: 
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - curl
        - wget
        - unzip
        - git 
        - apache2

    - name: Installing ca certificates
      shell: apt -y install lsb-release apt-transport-https ca-certificates

    - name: adding the ondrej php ppa
      apt_repository:
        repo="ppa:ondrej/php"
     
    - name: updating and upgrading apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Installing php8.1 and the needed extensions
      apt:
         name: "{{ item }}"
         state: present
         update_cache: yes
      with_items: 
         - php8.1 
         - libapache2-mod-php
         - php8.1-mysql
         - php8.1-common
         - php8.1-mysql
         - php8.1-xml
         - php8.1-xmlrpc
         - php8.1-curl
         - php8.1-gd
         - php8.1-imagick
         - php8.1-cli
         - php8.1-dev
         - php8.1-imap
         - php8.1-mbstring
         - php8.1-opcache
         - php8.1-soap
         - php8.1-zip
         - php8.1-intl
