---
- name: Deploying a laravel app
  hosts: all
  become: false
  become_user: vagrant
  vars:
    db_user: demoproject
    db_pass: demoproject
    db_name: demoproject
    diretory: suleiman-demo-project
    app_name: laravel

  tasks:     
    - name: Copy Script to remote
      ansible.builtin.copy:
        src: ~/ansible/files/laravel
        dest: ~/laravel
        owner: vagrant
        group: vagrant
        mode: '0777'
